### PR TITLE
If a feed is dead, indicate it to the user

### LINKED ISSUE #172: Idea: tell user when a feed seems to be dead
Hello!

I was doing a little re-organizing of the labels for my feeds and realized that one of them hadn't been updated in multiple years.

I looked a little bit in the feedbin code for where the request is made and found this bit: https://github.com/feedbin/refresher/blob/219657026ebfd3b21cfb18c99c43476a246cbda5/app/models/fetched.rb#L22-L40

If I'm understanding it right, unparseable feeds are treated as empty feeds.

The reason I like to use feedbin is to help keep track of things. For me, I would appreciate knowing if a feed has stopped delivering information, so I can see if it was renamed or moved and then continue to keep track of it.

I'm not sure if it makes sense to tell them right away... maybe there's some momentary downtime for a blog, but it's not truly dead.

What do you think?

### PR DESCRIPTION
**Pull request by maxjacobson**
fix #172 

requires https://github.com/feedbin/refresher/pull/7

### CODE REVIEW

**Comment by maxjacobson** [comment]
@benubois I'm not 100% sure if this works because I had some issues getting the app running locally... apologies! also did not mean to make so many changes to the sql file...

what do you think of the idea?

**Comment by maxjacobson** [comment]
ah, now travis is having the same issues I was having locally

**Comment by benubois** [comment]
Hi @maxjacobson,

I think this sounds like a great idea! A few thoughts on the approach:

- How about we save HTTP status codes in an integer array field on the feed and calculate `alive?` based on the last XX status codes. This might be a stronger indicator because it could help weed out transient failures.
- This might mean tracking success status codes (i.e. 200, 304 as well)
- Feedbin checks thousands of feeds per second so I'd rather not hit the database for every check. Maybe to get around this, one refresh cycle per hour/day/period could get a flag to indicate it should be sending back status codes. As an example check out the [`priority?`](https://github.com/feedbin/feedbin/blob/35124edc5930419075708b998e0436edcde662e3/app/workers/feed_refresher_scheduler.rb#L30-L32) method on the job that schedules feed refreshes.
- Instead of the new `FeedSeemsDead` job class I think all of this could piggyback on `FeedRefresherReceiver`.
- UI-wise I feel like this information would be best displayed on the [Feeds](https://feedbin.com/settings/feeds) page.

If you're interested in continuing to work on this and think it would be helpful to have you local Feedbin install working, I'm happy to troubleshoot your install. What issue are you seeing?

I don't currently have travis working due to some issues getting OpenCV set up on travis.

Thanks!

**Comment by maxjacobson** [comment]
Thanks for taking a look, Ben! The feedback makes a lot of sense. I would be happy to make those changes, although I'll need some time. If you're jazzed on the idea and want to run with it, I won't be offended :smile:.

I was having the same opencv issues reported by https://github.com/feedbin/feedbin/issues/171 and in the travis build

**Comment by benubois** [comment]
Hi @maxjacobson,

Cool! I'm happy to add it to my own list, but the list is long, and this may not be a priority anytime soon. 

As far as opencv goes, if you're trying to get it installed on a Mac, I think I installed it through homebrew.

Maybe something like `brew install homebrew/science/opencv`

If you're trying to get it installed on Linux I think the `libopencv-dev` package has what you need so with apt: `apt-get install libopencv-dev`

**Comment by benubois** [comment]
Closing for now. Feel free to submit a new PR if you ever want to resume work on this. Thanks!

**Pull request closed without merging**
