### PR TITLE
Add rake task to promote users to admin

### LINKED ISSUE #398: Promoting user to admin status
Hello,

As far as I can tell from the source code there is no way to make a user an admin.

From my understanding an admin has these capabilities:

- Delete users through the admin page
- Access sidekiq trough `/sidekiq`

I ended up doing this:

```sql
UPDATE users SET admin=true WHERE id=1
```

This should be a least documented. A good way to handle admins would be to add a rake task, maybe? If you agree I could make a PR.

### PR DESCRIPTION
**Pull request by angristan**
Fix #398

### CODE REVIEW

**Comment by angristan** [comment]
Hi 👋 Just wanted to bump this in case it went under your radar

**Comment by benubois** [comment]
Sure! Happy to accept something for this. 

Not sure how a rake task would accomplish this. Maybe an environment variable like with the billing functionality?

**Comment by angristan** [comment]
How would you implement this? You would add a check during the startup that would do a `User.find().update()` if the variable is set? To me, there are some drawbacks to this method:

- It adds yet another env variable
- It doesn't really belong there since it ends up altering the database, env should be for configuration only
- It adds instructions to the boot process
- It requires a restart to add an admin (and more if you make a typo)
- It's pretty easy to add support for removing an admin to the rake task, but with an env variables you would have to add more checks or another variable

What do you think?

**Comment by benubois** [comment]
Whoops replied to the wrong thing! Sorry.

**Comment by benubois** [comment]
Thanks!

**Comment by angristan** [comment]
Oh yeah if you were talking about #406, that would make more sense 😄 No problem!

**Comment by benubois** [comment]
That’s the one!

**Pull request merged**
